### ISSUE TITLE
Instructions on  https://hub.docker.com/r/solidconformancetestbeta/conformance-test-harness are outdated

### ISSUE THREAD

**Issue by michielbdejong** [solid/specification-tests#26]
I have `nss.env`:
```env
SOLID_IDENTITY_PROVIDER=https://solidcommunity.net
USERS_ALICE_WEBID=https://solidtestsuite.solidcommunity.net/profile/card#me
USERS_ALICE_CLIENTSECRET=Testing123
USERS_BOB_WEBID=https://solid-crud-tests-example-2.solidcommunity.net/profile/card#me
USERS_BOB_CLIENTSECRET=123
RESOURCE_SERVER_ROOT=https://solidtestsuite.solidcommunity.net
TEST_CONTAINER=/pod-owner/shared-test/
```
And `nss.sh`:
```sh
#!/bin/bash

 # This uses the test harness docker image with the default tests pulled from a repository.
 # Environment variables are defined in an `env` file in the directory from which you run this script.

 mkdir reports/nss
 docker pull solidconformancetestbeta/conformance-test-harness
 docker run -i --rm \
 -v "$(pwd)"/reports/nss:/reports \
 --env-file=nss.env solidconformancetestbeta/conformance-test-harness \
 --output=/reports --target=nss
```
When I run `sh ./nss.sh` I see:
```sh
$ sh nss.sh 
mkdir: reports/nss: File exists
Using default tag: latest
latest: Pulling from solidconformancetestbeta/conformance-test-harness
Digest: sha256:e4a751e68fe298c1d17f3ef033ce3977a2821c29f3e342fb3f38257bd6392262
Status: Image is up to date for solidconformancetestbeta/conformance-test-harness:latest
docker.io/solidconformancetestbeta/conformance-test-harness:latest
Oct 12, 2021 1:18:26 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 1.0.2
Oct 12, 2021 1:18:27 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.4.2.Final
Oct 12, 2021 1:18:27 PM io.quarkus.bootstrap.runner.Timing printStartupTime
INFO: testharness 1.0.2 on JVM (powered by Quarkus 2.3.0.Final) started in 3.755s. 
Oct 12, 2021 1:18:27 PM io.quarkus.bootstrap.runner.Timing printStartupTime
INFO: Profile prod activated. 
Oct 12, 2021 1:18:27 PM io.quarkus.bootstrap.runner.Timing printStartupTime
INFO: Installed features: [cdi, config-yaml, hibernate-validator, qute]
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-10-12 13:18:28,289 INFO  [org.sol.tes.con.Config] (main) Subjects URL:   file:/data/test-subjects.ttl
2021-10-12 13:18:28,369 INFO  [org.sol.tes.con.Config] (main) Sources:        [https://github.com/solid/specification-tests/protocol/solid-protocol-test-manifest.ttl, https://github.com/solid/specification-tests/web-access-control/web-access-control-test-manifest.ttl, https://github.com/solid/specification-tests/protocol/solid-protocol-spec.ttl, https://github.com/solid/specification-tests/web-access-control/web-access-control-spec.ttl]
2021-10-12 13:18:28,373 INFO  [org.sol.tes.con.Config] (main) Path mappings:  [https://github.com/solid/specification-tests => file:///data]
2021-10-12 13:18:28,375 INFO  [org.sol.tes.con.Config] (main) Target server:  file:/data/nss
2021-10-12 13:18:28,387 INFO  [org.sol.tes.uti.DataRepository] (main) Loading file:/data/protocol/solid-protocol-test-manifest.ttl with base https://github.com/solid/specification-tests/protocol/solid-protocol-test-manifest.ttl
2021-10-12 13:18:28,640 INFO  [org.sol.tes.uti.DataRepository] (main) Loading file:/data/web-access-control/web-access-control-test-manifest.ttl with base https://github.com/solid/specification-tests/web-access-control/web-access-control-test-manifest.ttl
2021-10-12 13:18:28,656 INFO  [org.sol.tes.uti.DataRepository] (main) Loading file:/data/protocol/solid-protocol-spec.ttl with base https://github.com/solid/specification-tests/protocol/solid-protocol-spec.ttl
2021-10-12 13:18:28,687 INFO  [org.sol.tes.uti.DataRepository] (main) Loading file:/data/web-access-control/web-access-control-spec.ttl with base https://github.com/solid/specification-tests/web-access-control/web-access-control-spec.ttl
2021-10-12 13:18:28,785 ERROR [org.sol.tes.ConformanceTestHarness] (main) Cannot run test suites: org.solid.testharness.utils.TestHarnessInitializationException: No config found for server: file:/data/nss
	at org.solid.testharness.config.TestSubject.lambda$loadTestSubjectConfig$1(TestSubject.java:87)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.solid.testharness.config.TestSubject.loadTestSubjectConfig(TestSubject.java:86)
	at org.solid.testharness.config.TestSubject_ClientProxy.loadTestSubjectConfig(TestSubject_ClientProxy.zig:186)
	at org.solid.testharness.ConformanceTestHarness.runTestSuites(ConformanceTestHarness.java:147)
	at org.solid.testharness.ConformanceTestHarness_ClientProxy.runTestSuites(ConformanceTestHarness_ClientProxy.zig:246)
	at org.solid.testharness.Application.run(Application.java:157)
	at org.solid.testharness.Application_ClientProxy.run(Application_ClientProxy.zig:129)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:123)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at org.solid.testharness.Application.main(Application.java:171)

Oct 12, 2021 1:18:28 PM io.quarkus.bootstrap.runner.Timing printStopTime
INFO: testharness stopped in 0.007s
```

I think the URL `file:/data/nss` refers to [the entry for 'nss'](https://github.com/solid/specification-tests/blob/main/test-subjects.ttl#L73), read from the `/data/test-subjects.ttl` file inside the container.

But apparently there is some config I forgot to add, or that I referred to incorrectly?

**Comment by edwardsph** [comment]
There are 4 authentication options described in the doc - I think you need to look at "Session-based Login" for NSS

**Comment by michielbdejong** [comment]
Thanks, that worked! Will leave this issue open for the outdated instructions that are still on Docker hub
